### ISSUE TITLE
API 为什么都没了？

### ISSUE THREAD

**Issue by maxtcarry** [c-zhuo/easycanvas#13]
我记得之前是有API文档的
 现在我想写东西都不知道怎么写了

**Comment by c-zhuo** [comment]
教程在https://c-zhuo.github.io/easycanvas/
API文档这个周末我补上，半年前的API文档还是markdown写的，一些信息过时了

**Comment by togoog** [comment]
现在API文档上面，有很多demo都错误了

**Comment by c-zhuo** [comment]
API参考https://c-zhuo.github.io/easycanvas/#Sprite-API
