### ISSUE TITLE
如何设置样式啊？没有文档吗？样式的参数没有文档？

### ISSUE THREAD

**Issue by Q956164483** [c-zhuo/easycanvas#17]

**Comment by c-zhuo** [comment]
文档还在理，不过demo里包含了大部分的样式参数，并且参数的命名参考了css，可以参考css的用法。
最近工作比较忙，争取尽快吧。

**Comment by Q956164483** [comment]
求参数啊，可以私聊先发我份不？像什么半圆，圆环这些都不知道怎么画

**Comment by Q956164483** [comment]
方便告诉下微信或者qq不？我qq 956164483

**Comment by c-zhuo** [comment]
半圆、圆环用图片吧，没有这些API
考虑到实际的应用一般都是图片组成的，很少是各种形状拼出来的，暂时不会支持点、线这种绘制

**Comment by Q956164483** [comment]
大哥，请教个问题，如何设置旋转的中心点位置啊？

**Comment by c-zhuo** [comment]
现在是rx和ry，后面可能会改。
可能会往rotateLeft和rotateTop上考虑，毕竟rotateCenterLeft有些长了

**Comment by c-zhuo** [comment]
https://c-zhuo.github.io/easycanvas/#Sprite-API
