### ISSUE TITLE
有没有Easycanvas.webglShapes.custom使用纹理贴图的demo呀?

### ISSUE THREAD

**Issue by cyitianyou** [c-zhuo/easycanvas#18]
类似于这样的，我只找到了使用colors的demo,可以使用img吗?
`Easycanvas.webglShapes.custom({`
 ` 　　　vertices: vertices,`
 ` 　　　indices: indices,`
 ` 　　　textures: textures,`
 ` 　　　img: 'https://raw.githubusercontent.com/c-zhuo/tanyitan/3d/debug/docs/stone.jpg'`
`})`

**Comment by c-zhuo** [comment]
可以的，参考demos里的plugin.webgl.3ds-loader.html
demo里的colors2属性是debug的时候加上的，可以忽略。

**Comment by cyitianyou** [comment]
找到了,非常感谢!
