### ISSUE TITLE
Chrome任务管理器显示GPU内存过高的问题

### ISSUE THREAD

**Issue by cyitianyou** [c-zhuo/easycanvas#20]
您好！
我在Canvas画布上显示了一个`Easycanvas.webglShapes.custom`组件，
跟随鼠标的mousemove事件通过`this.updateWebglStyle("vertices")`的方式不断的修改组件的顶点坐标。
操作几次之后Chrome浏览器显示**当前GPU内存超过1G以上**，整个浏览器会变得比较卡
想问下这类现象是因为WebGL中的缓存没有及时释放的原因吗？这种问题可以通过js代码解决吗？

**Comment by c-zhuo** [comment]
嗯应该是updateWebglStyle时没有释放缓存，晚上到家看一下

**Comment by c-zhuo** [comment]
这两天发个版本修复；可以暂时在updateWebglStyle上面包装一个新的API使用，验证一下是否解决
例如
Easycanvas.sprite.prototype.updateWebglStyle_fix = function (key, value) {
    if (this.webgl && this.webgl[key]) {
        this.$canvas.$gl.deleteBuffer(this.webgl[key].$cacheBuffer);
    }

    this.updateWebglStyle(key, value);
}

**Comment by cyitianyou** [comment]
好的，我先按照您的方法测试一下。
期待Easycanvas的新版本！

**Comment by cyitianyou** [comment]
您好！
使用您的修复方法之后，经测试，浏览器内存保持在一个稳定状态，但是GPU的使用率一直接近100%的程度。
目前考虑在不需要的时候使用`$app.pause()`方法暂停Webgl的渲染,应该能降低GPU的使用率。
感谢您的支持！
![image](https://user-images.githubusercontent.com/16968587/63082774-b16a6a00-bf79-11e9-8430-1661d617ca7e.png)

**Comment by cyitianyou** [comment]
试验发现setMaxFps方法更好用一点！

**Comment by c-zhuo** [comment]
@cyitianyou 好的，这样的话也可能是mousemove的触发频率太高了，例如一帧触发了多次mousemove。
可以参考
sprite.addEventListener('mousemove', somehandle, 20)
绑定事件，设置触发间隔，单位ms
