### ISSUE TITLE
IOS 平台 点击事件偏移

### ISSUE THREAD

**Issue by 80boys** [c-zhuo/easycanvas#22]
IOS 平台 点击事件有偏移,  并没有使用缩放属性, 事件偏移

**Comment by c-zhuo** [comment]
iOS真机 还是 Chrome的mobile模式？
是对某个Sprite的有偏移还是整体都偏移了，<canvas>标签本身有使用css的transform吗？

**Comment by 80boys** [comment]
IOS真机,  Chrome的mobile模式没有任何问题, 所有Sprite都偏移
没有对canvas标签使用 transform
PS:  之前开发Sprite使用css scale 缩放,  后发现点击事件偏移,  
然后我们就删除了scale,  发现安卓没问题IOS还是有问题

`
this.painter.add(
                Easycanvas.class.sequence({
                    props: {},
                    style: {
                        tx: this.width / 3,  ty: this.height / 2,
                        backgroundColor:"blue",
                        tw: this.width * this.scale / 4, th: this.height,
                        opacity: 0, zIndex:9999
                    },
                    events: {
                        touchstart: ()=>{ 
                            console.log( "点击事件" )
                        }
                    }
                })
            )
`

**Comment by 80boys** [comment]
> iOS真机 还是 Chrome的mobile模式？
> 是对某个Sprite的有偏移还是整体都偏移了，canvas标签本身有使用css的transform吗？


IOS真机,  Chrome的mobile模式没有任何问题, 所有Sprite都偏移
没有对canvas标签使用 transform
PS:  之前开发Sprite使用css scale 缩放,  后发现点击事件偏移,  
然后我们就删除了scale,  发现安卓没问题IOS还是有问题

`this.painter.add(
                Easycanvas.class.sequence({
                    props: {},
                    style: {
                        tx: this.width / 3,  ty: this.height / 2,
                        backgroundColor:"blue",
                        tw: this.width * this.scale / 4, th: this.height,
                        opacity: 0, zIndex:9999
                    },
                    events: {
                        touchstart: ()=>{ 
                            console.log( "点击事件" )
                        }
                    }
                })
        )
`

**Comment by c-zhuo** [comment]
@80boys 升一下版本试试。看起来是比较早期的版本，可能存在个别bug。后来的版本对Sprite的属性名称有调整，例如tw改为了width，和css对齐，sequence组件的API也有部分调整。
